name: Auto create CODEOWNERS on new repo

on:
  repository:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  add-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Create CODEOWNERS file in the new repo
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;

            const content = "# Code ownership rules\n.github/ @HausAnalytics/squad-infra-eng\n";

            const path = ".github/CODEOWNERS";

            try {
              await github.rest.repos.createOrUpdateFileContents({
                owner,
                repo,
                path,
                message: "Add default CODEOWNERS file",
                content: Buffer.from(content).toString("base64"),
                branch: "main"
              });

              core.info(`✅ CODEOWNERS added to ${owner}/${repo}`);
            } catch (e) {
              core.setFailed(`❌ Failed: ${e.message}`);
            }
